export const guests = [
  {
    name: 'Reinaldo González',
    phone: '12623647385',
    personas: 3,
    title: 'Sr. Reinaldo González y familia',
  },
  {
    name: 'Nicolas Bravo',
    phone: '33749455610',
    personas: 1,
    title: 'Sr. Nicolas Bravo',
  },
  {
    name: 'Melissa Bravo',
    phone: '33767371115',
    personas: 2,
    title: 'Srta. Melissa Bravo y Sr.',
  },
  {
    name: 'Manuel Ruano',
    phone: '16472421689',
    personas: 1,
    title: 'Sr. Manuel Ruano',
  },
  {
    name: 'Nicole Ruano',
    phone: '16474251689',
    personas: 3,
    title: 'Srta. Nicole Ruano e hijos',
  },
  {
    name: 'Juan Pablo Londoño',
    phone: '16475756286',
    personas: 4,
    title: 'Sr. Juan Pablo Londoño y familia',
  },
   {
     name: 'Dolores Negrete',
     phone: '0992631662',
     personas: 1,
     title: 'Sra. Dolores Negrete',
   },
  {
    name: 'Alberto Leiva',
    phone: '0999069878',
    personas: 2,
    title: 'Sr. Alberto Leiva y esposa',
  },
  {
    name: 'Pablo Leiva',
    phone: '0995399181',
    personas: 2,
    title: 'Sr. Pablo Leiva y esposa',
  },
  {
    name: 'Diego Leiva',
    phone: '0988175266',
    personas: 3,
    title: 'Sr. Diego Leiva y familia',
  },
  {
    name: 'Cristian Leiva',
    phone: '0999752039',
    personas: 4,
    title: 'Sr. Cristian Leiva y familia',
  },
  {
    name: 'Cesar Leiva',
    phone: '0984202774',
    personas: 5,
    title: 'Sr. Cesar Leiva y familia',
  },
  {
    name: 'Catalina González',
    phone: '0997974886',
    personas: 1,
    title: 'Sra. Catalina González',
  },
  {
    name: 'Diego Beltrán',
    phone: '0967084060',
    personas: 3,
    title: 'Sr. Diego Beltrán y familia',
  },
  {
    name: 'Marco Salazar',
    phone: '0999940505',
    personas: 3,
    title: 'Sr. Marco Salazar y familia',
  },
  {
    name: 'Handel Terán',
    phone: '0997309418',
    personas: 2,
    title: 'Sr. Handel Terán y familia',
  },
  {
    name: 'Xavier González',
    phone: '0999851195',
    personas: 2,
    title: 'Sr. Xavier González y esposa',
  },
  {
    name: 'Alvaro Ruano',
    phone: '0986416783',
    personas: 3,
    title: 'Sr. Alvaro Ruano y familia',
  },
  {
    name: 'Ximena Ruano',
    phone: '0984694898',
    personas: 3,
    title: 'Sra. Ximena Ruano e hijos',
  },
  {
    name: 'Santiago Ruano',
    phone: '0999248645',
    personas: 3,
    title: 'Sr. Santiago Ruano y familia',
  },
  {
    name: 'Dario Andrade',
    phone: '0984538387',
    personas: 3,
    title: 'Sr. Dario Andrade y familia',
  },
  {
    name: 'Jhael Ruano',
    phone: '0998940696',
    personas: 1,
    title: 'Sra. Jhael Ruano',
  },
  {
    name: 'Yasmine Andrade',
    phone: '0979200336',
    personas: 3,
    title: 'Sra. Yasmine Andrade e hijos',
  },
  {
    name: 'Cira Ruano',
    phone: '0995902529',
    personas: 2,
    title: 'Sra. Cira Ruano e hija',
  },
  {
    name: 'Christian Flores',
    phone: '0984302497',
    personas: 5,
    title: 'Sr. Christian Flores y familia',
  },
  {
    name: 'Rocio Ruano',
    phone: '0987727279',
    personas: 2,
    title: 'Sra. Rocio Ruano e hijo',
  },
  {
    name: 'Sofía Cadena',
    phone: '0992032819',
    personas: 3,
    title: 'Sra. Sofía Cadena e hijos',
  },
  {
    name: 'Ramiro Ruano',
    phone: '0999821190',
    personas: 2,
    title: 'Sr. Ramiro Ruano y esposa',
  },
  {
    name: 'Micaela Ruano',
    phone: '0998726087',
    personas: 2,
    title: 'Sra. Micaela Ruano e hijo',
  },
  {
    name: 'Marcelo Ruano',
    phone: '0960052853',
    personas: 1,
    title: 'Sr. Marcelo Ruano',
  },
  {
    name: 'Patricio Cevallos',
    phone: '',
    personas: 2,
    title: 'Sr. Patricio Cevallos y esposa',
  },
  {
     name: 'Sara Vaca',
     phone: '0960174982',
     personas: 3,
     title: 'Sra. Sara Vaca e hijos',
   },
  // {
  //   name: 'Débora Castillo',
  //   phone: '',
  //   personas: 1,
  //   title: 'Sra. Débora Castillo',
  // },
  {
    name: 'Bolívar Castillo',
    phone: '0996515150',
    personas: 1,
    title: 'Sr. Bolívar Castillo',
  },
  {
    name: 'Javier Vaca',
    phone: '0988252014',
    personas: 6,
    title: 'Sr. Javier Vaca y familia',
  },
  {
    name: 'Santiago Castillo',
    phone: '0986718564',
    personas: 4,
    title: 'Sr. Santiago Castillo y familia',
  },
  {
    name: 'Armando Mera',
    phone: '0993369544',
    personas: 4,
    title: 'Sr. Armando Mera y familia',
  },
  {
    name: ' Pablo Aguirre',
    phone: '0983127557',
    personas: 4,
    title: 'Sr. Pablo Aguirre y familia',
  },
  {
    name: 'Alejandro Godoy',
    phone: '0967718850',
    personas: 4,
    title: 'Sr. Alejandro Godoy y familia',
  },
  {
    name: 'Oscar Cevallos',
    phone: '0995324040',
    personas: 2,
    title: 'Sr. Oscar Cevallos y esposa',
  },
  {
    name: 'Juan Carlos Cevallos',
    phone: '0984572376',
    personas: 2,
    title: 'Sr. Juan Carlos Cevallos y esposa',
  },
  {
    name: 'René Chamorro',
    phone: '',
    personas: 4,
    title: 'Sra. René Chamorro e hijas',
  },
  {
    name: 'Carlos Mera',
    phone: '0959220276',
    personas: 4,
    title: 'Sr. Carlos Mera y familia',
  },
  {
    name: 'Paúl Pozo',
    phone: '0995635189',
    personas: 1,
    title: 'Sr. Paúl Pozo',
  },
  {
    name: 'José Ponce',
    phone: '',
    personas: 2,
    title: 'Sr. José Ponce y esposa',
  },
  {
    name: 'Christian Ponce',
    phone: '0984268869',
    personas: 2,
    title: 'Sr. Christian Ponce y esposa',
  },
  {
    name: 'Santiago Tapia',
    phone: '',
    personas: 4,
    title: 'Sr. Santiago Tapia y familia',
  },
  {
    name: 'Omar Ponce',
    phone: '',
    personas: 4,
    title: 'Sr. Omar Ponce y familia',
  },
  {
    name: 'Edwin Chamorro',
    phone: '',
    personas: 2,
    title: 'Sr. Edwin Chamorro y esposa',
  },
  {
    name: 'Lenin Naranjo',
    phone: '',
    personas: 4,
    title: 'Sr. Lenin Naranjo y familia',
  },
  {
    name: 'Andrés Chamorro',
    phone: '',
    personas: 2,
    title: 'Sr. Andrés Chamorro',
  },
  {
    name: 'Eliana Morillo',
    phone: '0968596502',
    personas: 1,
    title: 'Srta. Eliana Morillo',
  },
  {
    name: 'Álvaro Carrera',
    phone: '0983936154',
    personas: 1,
    title: 'Sr. Álvaro Carrera',
  },
  {
    name: 'María José Puente',
    phone: '0995005460',
    personas: 1,
    title: 'Srta. María José Puente',
  },
  {
    name: 'Karen García',
    phone: '0998922853',
    personas: 1,
    title: 'Srta. Karen García',
  },
  {
    name: 'Andrés Baldeon',
    phone: '0984677673',
    personas: 1,
    title: 'Sr. Andrés Baldeon',
  },
  {
    name: 'Marco Lozano',
    phone: '0984034654',
    personas: 1,
    title: 'Sr. Marco Lozano',
  },
  {
    name: 'Ana Figueroa',
    phone: '0995378643',
    personas: 1,
    title: 'Srta. Ana Figueroa',
  },
  {
    name: 'William Marcillo',
    phone: '0984848166',
    personas: 2,
    title: 'Sr. William Marcillo y Sra.',
  },
  {
    name: 'Anghelo Lozano',
    phone: '0998124392',
    personas: 1,
    title: 'Sr. Anghelo Lozano',
  },
  {
    name: 'Diego Lozano',
    phone: '0992802115',
    personas: 1,
    title: 'Sr. Diego Lozano',
  }
];
